
# AUTO-GENERATED by JustCmul8 codeGenerator.ts
import simpy
import random
import json
import logging
import copy

# ── Configuration ──────────────────────────────────────────────────────────────
DURATION = 15
TICK_INTERVAL = 15
NODE_CONFIG = json.loads(r"""{"n1":{"nodeType":"source","label":"Arrival Point","params":{"arrivalRate":0.2,"distribution":"deterministic","routingMode":"round_robin"}},"n2":{"nodeType":"queue","label":"Waiting Line","params":{}},"n3":{"nodeType":"resource","label":"Staff / Machine","params":{"capacity":1,"serviceTimeMean":4,"serviceDistribution":"deterministic"}},"n4":{"nodeType":"sink","label":"Exit Point","params":{}}}""")
EDGES = json.loads(r"""[{"id":"e1","source":"n1","target":"n2"},{"id":"e2","source":"n2","target":"n3"},{"id":"e3","source":"n3","target":"n4"}]""")

# ── Log Buffer ─────────────────────────────────────────────────────────────────
log_buffer = []
entity_counter = [0]
stats = {}
active_processes_by_node = {}
global_events = {}

def next_entity_id():
    entity_counter[0] += 1
    return entity_counter[0]

def log_event(sim_time, entity_id, node_id, node_label, event):
    log_buffer.append({
        "simTime": sim_time,
        "entityId": entity_id,
        "nodeId": node_id,
        "nodeLabel": node_label,
        "event": event
    })

# ── Distributions ──────────────────────────────────────────────────────────────
def sample(dist_type, mean, std=None):
    if dist_type == "exponential":
        return random.expovariate(1.0 / mean) if mean > 0 else 0
    elif dist_type == "uniform":
        return random.uniform(mean * 0.5, mean * 1.5)
    elif dist_type == "normal":
        s = std if std is not None else mean * 0.3
        return max(0, random.gauss(mean, s))
    elif dist_type == "deterministic":
        return max(0, mean)
    elif dist_type == "poisson":
        return random.expovariate(1.0 / mean) if mean > 0 else 0
    else:
        return random.expovariate(1.0 / mean) if mean > 0 else 0

# ── Build adjacency ────────────────────────────────────────────────────────────
out_edges = {}
for edge in EDGES:
    src = edge["source"]
    if src not in out_edges:
        out_edges[src] = []
    out_edges[src].append(edge["target"])

rr_counters = {}
def get_next_targets(node_id, routing_mode="round_robin"):
    """Returns a list of target node IDs based on the routing mode."""
    targets = out_edges.get(node_id, [])
    if not targets:
        return []
    if routing_mode == "broadcast":
        return targets  # send to ALL
    if len(targets) == 1:
        return [targets[0]]
    # Round-robin (default, also used for "priority" as a fallback)
    if node_id not in rr_counters:
        rr_counters[node_id] = 0
    idx = rr_counters[node_id] % len(targets)
    rr_counters[node_id] += 1
    return [targets[idx]]

def get_next_target(node_id):
    """Legacy single-target helper — returns first round-robin target."""
    targets = get_next_targets(node_id, "round_robin")
    return targets[0] if targets else None

def get_target_for_decision(node_id):
    cfg = NODE_CONFIG[node_id]
    routes = cfg["params"].get("routes", [])
    r = random.random()
    cum = 0.0
    for route in routes:
        cum += route["probability"]
        if r <= cum:
            return route["targetId"]
    return routes[0]["targetId"] if routes else None

# ── Stats helpers ──────────────────────────────────────────────────────────────
def init_stats():
    for nid, cfg in NODE_CONFIG.items():
        stats[nid] = {
            "nodeId": nid,
            "nodeType": cfg["nodeType"],
            "label": cfg["label"],
            "entitiesIn": 0,
            "entitiesOut": 0,
            "currentDepth": 0,
            "busyCount": 0,
            "busy_seconds": 0.0,
            "last_busy_change": 0.0,
            "capacity": cfg["params"].get("capacity", 1),
            "waits": [],
            "services": [],
            "latencies": [],
            "utilization": 0.0,
            "avgWaitTime": 0.0,
            "avgServiceTime": 0.0,
            "renegeCount": 0,
            "droppedCount": 0,
        }

def snapshot_stats(env):
    snap = {}
    for nid, s in stats.items():
        # G19 fix: compute time-weighted utilization, not instantaneous
        busy_so_far = s["busy_seconds"]
        if s["busyCount"] > 0:
            busy_so_far += (env.now - s["last_busy_change"]) * s["busyCount"]
        elapsed = env.now if env.now > 0 else 1
        util = busy_so_far / (elapsed * max(1, s["capacity"])) if s["capacity"] > 0 else 0
        
        node_type = s["nodeType"]
        if node_type == "container":
            con = resources.get(nid)
            level = con.level if con else 0
        else:
            level = s.get("level")

        snap[nid] = {
            "nodeId": nid,
            "nodeType": node_type,
            "label": s["label"],
            "entitiesIn": s["entitiesIn"],
            "entitiesOut": s["entitiesOut"],
            "currentDepth": s["currentDepth"],
            "utilization": min(1.0, util),
            "avgWaitTime": sum(s["waits"]) / len(s["waits"]) if s["waits"] else 0,
            "avgServiceTime": sum(s["services"]) / len(s["services"]) if s["services"] else 0,
            "renegeCount": s.get("renegeCount", 0),
            "droppedCount": s.get("droppedCount", 0),
            "level": level,
        }
        if s["latencies"]:
            snap[nid]["avgLatency"] = sum(s["latencies"]) / len(s["latencies"])
    return snap

# ── Helpers ────────────────────────────────────────────────────────────────────
def do_resource_service(env, eid, node_id, cfg, s, resources, queued_at):
    params = cfg["params"]
    label = cfg["label"]
    wait_time = env.now - queued_at
    s["waits"].append(wait_time)
    # G19 fix: accumulate busy-time before changing busyCount
    if s["busyCount"] > 0:
        s["busy_seconds"] += (env.now - s["last_busy_change"]) * s["busyCount"]
    s["last_busy_change"] = env.now
    s["busyCount"] += 1
    svc_time = sample(
        params.get("serviceDistribution", "exponential"),
        params.get("serviceTimeMean", 1)
    )
    log_event(env.now, eid, node_id, label, "service_start")
    yield env.timeout(svc_time)
    s["services"].append(svc_time)
    # G19 fix: accumulate busy-time before decrementing
    s["busy_seconds"] += (env.now - s["last_busy_change"]) * s["busyCount"]
    s["last_busy_change"] = env.now
    s["busyCount"] -= 1
    log_event(env.now, eid, node_id, label, "service_end")
    s["currentDepth"] -= 1
    s["entitiesOut"] += 1
    next_id = get_next_target(node_id)
    if next_id:
        yield env.process(entity_process(env, eid, next_id, resources))

# ── SimPy Processes ────────────────────────────────────────────────────────────
def entity_process(env, eid, node_id, resources, entity_attrs=None):
    if entity_attrs is None:
        entity_attrs = {"id": eid, "priority": 3, "entityClass": "standard", "arrivalTime": env.now}
    cfg = NODE_CONFIG.get(node_id)
    if cfg is None:
        return

    node_type = cfg["nodeType"]
    label = cfg["label"]
    s = stats[node_id]
    s["entitiesIn"] += 1
    s["currentDepth"] += 1

    if node_type == "source":
        log_event(env.now, eid, node_id, label, "arrived")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "queue":
        log_event(env.now, eid, node_id, label, "queued")
        next_id = get_next_target(node_id)
        
        # If queue is connected to a resource, apply patience timeout here
        if next_id and NODE_CONFIG.get(next_id, {}).get("nodeType") in ("resource", "priority_resource"):
            params = cfg.get("params", {})
            dist = params.get("patienceDistribution", "none")
            
            res_node_id = next_id
            res_cfg = NODE_CONFIG[res_node_id]
            res_s = stats[res_node_id]
            res = resources[res_node_id]
            
            queued_at = env.now
            res_s["entitiesIn"] += 1
            res_s["currentDepth"] += 1
            
            with res.request() as req:
                if dist != "none":
                    if dist == "uniform":
                        p_min = params.get("patienceMin", 1)
                        p_max = params.get("patienceMax", 3)
                        patience = random.uniform(p_min, p_max)
                    elif dist == "exponential":
                        mean = params.get("patienceTimeout", 5)
                        patience = random.expovariate(1.0 / mean) if mean > 0 else 0
                    elif dist == "deterministic":
                        patience = params.get("patienceTimeout", 5)
                    else:
                        patience = 999999
                        
                    results = yield req | env.timeout(patience)
                    
                    if req in results:
                        s["currentDepth"] -= 1
                        s["entitiesOut"] += 1
                        yield env.process(do_resource_service(env, eid, res_node_id, res_cfg, res_s, resources, queued_at))
                    else:
                        log_event(env.now, eid, node_id, label, "reneged")
                        s["currentDepth"] -= 1
                        s["renegeCount"] = s.get("renegeCount", 0) + 1
                        res_s["currentDepth"] -= 1
                        return
                else:
                    yield req
                    s["currentDepth"] -= 1
                    s["entitiesOut"] += 1
                    yield env.process(do_resource_service(env, eid, res_node_id, res_cfg, res_s, resources, queued_at))
        else:
            s["currentDepth"] -= 1
            s["entitiesOut"] += 1
            if next_id:
                yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type in ("resource", "priority_resource"):
        res = resources[node_id]
        queued_at = env.now
        log_event(env.now, eid, node_id, label, "queued")
        with res.request() as req:
            yield req
            yield env.process(do_resource_service(env, eid, node_id, cfg, s, resources, queued_at))

    elif node_type == "service":
        params = cfg["params"]
        svc_time = sample(
            params.get("distribution", "exponential"),
            params.get("durationMean", 1)
        )
        
        def interruptible_delay(env, delay):
            try:
                log_event(env.now, eid, node_id, label, "service_start")
                yield env.timeout(delay)
                log_event(env.now, eid, node_id, label, "service_end")
            except simpy.Interrupt as i:
                log_event(env.now, eid, node_id, label, "interrupted")
                
        p = env.process(interruptible_delay(env, svc_time))
        if node_id not in active_processes_by_node: active_processes_by_node[node_id] = {}
        active_processes_by_node[node_id][eid] = p
        yield p
        if eid in active_processes_by_node[node_id]: del active_processes_by_node[node_id][eid]
        
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "decision":
        log_event(env.now, eid, node_id, label, "routed")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        target_id = get_target_for_decision(node_id)
        if target_id:
            yield env.process(entity_process(env, eid, target_id, resources, entity_attrs))

    elif node_type == "sink":
        log_event(env.now, eid, node_id, label, "completed")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1

    elif node_type == "store":
        store = resources.get(node_id)
        params = cfg["params"]
        
        if store.capacity != float('inf') and len(store.items) >= store.capacity:
            s["droppedCount"] += 1
            s["entitiesOut"] += 1
            s["currentDepth"] -= 1
            log_event(env.now, eid, node_id, label, "dropped")
            return

        if isinstance(store, simpy.PriorityStore):
            item = simpy.PriorityItem(entity_attrs.get("priority", 3), entity_attrs)
        else:
            item = entity_attrs

        yield store.put(item)
        s["currentDepth"] = len(store.items)
        
        if isinstance(store, simpy.FilterStore):
            prop = params.get("filterProperty", "entityClass")
            op = params.get("filterOperator", "==")
            val = params.get("filterValue", "")
            def filter_func(x):
                actual = x.get(prop, "") if isinstance(x, dict) else ""
                if op == "==": return str(actual) == str(val)
                if op == "!=": return str(actual) != str(val)
                return True
            got = yield store.get(filter_func)
        else:
            got = yield store.get()

        s["currentDepth"] = len(store.items)
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "channel":
        store = resources.get(node_id)
        params = cfg["params"]
        
        if store.capacity != float('inf') and len(store.items) >= store.capacity:
            s["droppedCount"] += 1
            s["entitiesOut"] += 1
            s["currentDepth"] -= 1
            log_event(env.now, eid, node_id, label, "dropped")
            return
            
        yield store.put(entity_attrs)
        s["currentDepth"] = len(store.items)
        
        delay = sample(params.get("delayDistribution", "deterministic"), params.get("propagationDelay", 0))
        log_event(env.now, eid, node_id, label, "transmitted")
        
        yield env.timeout(delay)
        
        yield store.get() # free capacity
        s["currentDepth"] = len(store.items)
        
        s["entitiesOut"] += 1
        s["latencies"].append(delay)
        log_event(env.now, eid, node_id, label, "received")
        
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))
            
    elif node_type == "broadcaster":
        log_event(env.now, eid, node_id, label, "broadcast")
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        targets = get_next_targets(node_id, "broadcast")
        for tgt in targets:
            cloned_attrs = copy.deepcopy(entity_attrs)
            env.process(entity_process(env, eid, tgt, resources, cloned_attrs))
            
    elif node_type == "container":
        params = cfg["params"]
        con = resources.get(node_id)
        fill_rate = params.get("fillRate", 1)
        
        if con.level + fill_rate <= con.capacity:
            yield con.put(fill_rate)
        else:
            # Drop or just try to put? In legacy JS it waits via putQ if it exceeds capacity.
            # SimPy Container put() blocks until there is enough capacity.
            yield con.put(fill_rate)
            
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "event_trigger":
        evt = global_events.get(node_id)
        if evt and not evt.triggered:
            evt.succeed()
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type in ("any_of", "all_of"):
        sources = [e["source"] for e in EDGES if e["target"] == node_id]
        evts = [global_events[src] for src in sources if src in global_events]
        if evts:
            if node_type == "any_of":
                yield env.any_of(evts)
            else:
                yield env.all_of(evts)
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = cfg["params"].get("targetId") or get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    elif node_type == "interrupter":
        target = cfg["params"].get("targetNodeId")
        cause = cfg["params"].get("cause", "Interrupted")
        if target and target in active_processes_by_node:
            for p_eid, p in list(active_processes_by_node[target].items()):
                if p.is_alive:
                    p.interrupt(cause)
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))

    else:
        s["currentDepth"] -= 1
        s["entitiesOut"] += 1
        next_id = get_next_target(node_id)
        if next_id:
            yield env.process(entity_process(env, eid, next_id, resources, entity_attrs))


def source_process(env, node_id, resources, total_arrived):
    cfg = NODE_CONFIG[node_id]
    params = cfg["params"]
    arrival_rate = params.get("arrivalRate", 1)
    distribution = params.get("distribution", "exponential")
    max_entities = params.get("maxEntities", None)
    routing_mode = params.get("routingMode", "round_robin")
    schedule = params.get("schedule", [])  # list of {simTime, count}
    schedule_recurring = params.get("scheduleRecurring", False)
    priority_level = params.get("priorityLevel", "standard")
    entity_class = params.get("entityClass", "customer")
    # Map priority level to numeric (lower = higher priority)
    priority_map = {"standard": 3, "priority": 2, "urgent": 1}
    priority_num = priority_map.get(priority_level, 3)

    def spawn_entity():
        eid = next_entity_id()
        total_arrived[0] += 1
        # Attach attributes to entity (stored in a context dict for downstream use)
        entity_attrs = {
            "id": eid,
            "priority": priority_num,
            "entityClass": entity_class,
            "arrivalTime": env.now,
        }
        log_event(env.now, eid, node_id, cfg["label"], "arrived")
        targets = get_next_targets(node_id, routing_mode)
        for target_id in targets:
            env.process(entity_process(env, eid, target_id, resources, entity_attrs))

    count = 0

    if schedule:
        # ── Schedule-based arrivals ──────────────────────────────────────────
        last_period_offset = 0.0
        while True:
            for entry in sorted(schedule, key=lambda e: e["simTime"]):
                fire_at = last_period_offset + entry["simTime"]
                if fire_at > DURATION:
                    return
                delay = max(0.0, fire_at - env.now)
                yield env.timeout(delay)
                if env.now > DURATION:
                    return
                for _ in range(entry.get("count", 1)):
                    if max_entities and count >= max_entities:
                        return
                    spawn_entity()
                    count += 1
            if not schedule_recurring:
                break
            # For recurring, advance period by the last entry's simTime
            last_period_offset += max(e["simTime"] for e in schedule)
    else:
        # ── Rate-based arrivals ──────────────────────────────────────────────
        while True:
            inter_arrival = sample(distribution, 1.0 / arrival_rate if arrival_rate > 0 else 1.0)
            yield env.timeout(inter_arrival)
            if env.now > DURATION:
                break
            if max_entities and count >= max_entities:
                break
            spawn_entity()
            count += 1

def tick_emitter(env, resources, total_arrived):
    while True:
        yield env.timeout(TICK_INTERVAL)
        snap = snapshot_stats(env)
        recent = list(log_buffer)
        log_buffer.clear()
        
        tick = {
            "type": "tick",
            "data": {
                "simTime": env.now,
                "wallElapsed": 0,
                "totalArrived": total_arrived[0],
                "totalCompleted": stats_total_completed(snap),
                "nodeStats": snap,
                "recentLogs": recent,
            }
        }
        emit_sim_tick(json.dumps(tick))

def stats_total_completed(snap):
    for nid, s in snap.items():
        if NODE_CONFIG[nid]["nodeType"] == "sink":
            return s["entitiesOut"]
    return 0

def run_simulation():
    env = simpy.Environment()
    global resources
    resources = {}
    total_arrived = [0]

    init_stats()

    for nid, cfg in NODE_CONFIG.items():
        n_type = cfg["nodeType"]
        if n_type in ("resource", "priority_resource"):
            cap = cfg["params"].get("capacity", 1)
            is_pre = cfg["params"].get("isPreemptive", False)
            if n_type == "priority_resource" or is_pre:
                resources[nid] = simpy.PriorityResource(env, capacity=max(1, cap))
            else:
                resources[nid] = simpy.Resource(env, capacity=max(1, cap))
        elif n_type == "store":
            cap = cfg["params"].get("capacity", -1)
            c = max(1, cap) if cap > 0 else float('inf')
            if cfg["params"].get("isPriority", False):
                resources[nid] = simpy.PriorityStore(env, capacity=c)
            elif cfg["params"].get("filterEnabled", False):
                resources[nid] = simpy.FilterStore(env, capacity=c)
            else:
                resources[nid] = simpy.Store(env, capacity=c)
        elif n_type == "channel":
            cap = cfg["params"].get("bufferCapacity", -1)
            c = max(1, cap) if cap > 0 else float('inf')
            resources[nid] = simpy.Store(env, capacity=c)
        elif n_type == "container":
            cap = cfg["params"].get("capacity", 1000)
            init_level = cfg["params"].get("initialLevel", 0)
            resources[nid] = simpy.Container(env, capacity=cap, init=init_level)
        elif n_type in ("event_trigger", "any_of", "all_of"):
            global_events[nid] = env.event()

    for nid, cfg in NODE_CONFIG.items():
        if cfg["nodeType"] == "source":
            env.process(source_process(env, nid, resources, total_arrived))

    env.process(tick_emitter(env, resources, total_arrived))

    env.run(until=DURATION)

    snap = snapshot_stats(env)
    remaining_logs = list(log_buffer)

    bottleneck_id = ""
    bottleneck_label = ""
    max_wait = -1
    for nid, s in snap.items():
        if NODE_CONFIG[nid]["nodeType"] in ("resource", "queue"):
            if s["avgWaitTime"] > max_wait:
                max_wait = s["avgWaitTime"]
                bottleneck_id = nid
                bottleneck_label = NODE_CONFIG[nid]["label"]

    result = {
        "type": "complete",
        "data": {
            "simType": "human_queue", # Extracted correctly ideally, but fine for Bank Tellers
            "totalSimTime": env.now,
            "totalArrived": total_arrived[0],
            "totalCompleted": stats_total_completed(snap),
            "bottleneckNodeId": bottleneck_id,
            "bottleneckLabel": bottleneck_label,
            "nodeStats": snap,
            "timeline": [],
            "logs": remaining_logs,
        }
    }
    
    emit_sim_result(json.dumps(result))

run_simulation()
