import type { SimResult } from "./types";

/**
 * Helper to split a script into lines with proper trailing newlines for Jupyter Notebook source arrays.
 */
function toSourceLines(text: string): string[] {
  const lines = text.split("\n");
  return lines.map((line, idx) => (idx < lines.length - 1 ? line + "\n" : line));
}

/**
 * Builds a valid Jupyter Notebook (.ipynb v4.5) object from the generated SimPy script.
 */
export function buildJupyterNotebook(
  pythonScript: string,
  projectName: string = "Simulation",
  result: SimResult | null = null
): Record<string, any> {
  const dateStr = new Date().toISOString().replace("T", " ").substring(0, 19) + " UTC";

  const introMarkdown = [
    `# ${projectName} - SimPy Discrete-Event Simulation\n`,
    `Generated by **JustCmul8** on \`${dateStr}\`.\n`,
    `\n`,
    `## Prerequisites\n`,
    `To run this notebook locally, ensure you have \`simpy\` installed:\n`,
    `\`\`\`bash\n`,
    `pip install simpy\n`,
    `\`\`\`\n`,
  ];

  // Runtime stubs prepended to allow standalone CPython / Jupyter execution
  const standaloneStubs = `# ── Browser Runtime Environment Stubs ─────────────────────────────────────────\n# In JustCmul8's web environment, these communicate with the WebWorker.\n# In standard Python, we stub them as no-ops or simple loggers.\ndef emit_sim_tick(payload): pass\ndef emit_sim_result(payload): pass\n\n`;

  const fullCode = standaloneStubs + pythonScript;

  const cells: any[] = [
    {
      cell_type: "markdown",
      metadata: {},
      source: introMarkdown,
    },
    {
      cell_type: "code",
      execution_count: null,
      metadata: {},
      outputs: [],
      source: toSourceLines(fullCode),
    },
  ];

  if (result) {
    const throughputPerSec =
      result.totalSimTime > 0 ? (result.totalCompleted / result.totalSimTime).toFixed(2) : "0";
    const avgCycle = result.cycleTimePercentiles?.mean != null
      ? `${result.cycleTimePercentiles.mean.toFixed(2)}s`
      : "N/A";
    const avgWait = result.waitTimePercentiles?.mean != null
      ? `${result.waitTimePercentiles.mean.toFixed(2)}s`
      : "N/A";

    const summaryMarkdown = [
      `## Simulation Results Snapshot\n`,
      `The last captured web run completed with:\n`,
      `- **Simulated Duration:** ${result.totalSimTime}s\n`,
      `- **Total Throughput:** ${result.totalCompleted} items (${throughputPerSec} items/s)\n`,
      `- **Average Cycle Time:** ${avgCycle}\n`,
      `- **Average Wait Time:** ${avgWait}\n`,
      `- **Bottleneck Station:** ${result.bottleneckLabel || result.bottleneckNodeId || "None"}\n`,
      result.costAnalysis
        ? `- **Total System Cost:** $${result.costAnalysis.totalSystemCost.toFixed(2)} ($${result.costAnalysis.costPerCompletedEntity.toFixed(2)}/unit)\n`
        : ``,
    ].filter(Boolean);

    cells.push({
      cell_type: "markdown",
      metadata: {},
      source: summaryMarkdown,
    });
  }

  return {
    cells,
    metadata: {
      language_info: {
        name: "python",
        version: "3.10.0",
      },
      kernelspec: {
        name: "python3",
        display_name: "Python 3",
      },
    },
    nbformat: 4,
    nbformat_minor: 5,
  };
}

/**
 * Triggers a browser file download of the Jupyter Notebook (.ipynb).
 */
export function downloadJupyterNotebook(
  pythonScript: string,
  projectName: string = "Simulation",
  result: SimResult | null = null
): void {
  const notebookObj = buildJupyterNotebook(pythonScript, projectName, result);
  const jsonContent = JSON.stringify(notebookObj, null, 2);
  const blob = new Blob([jsonContent], { type: "application/x-ipynb+json;charset=utf-8" });
  const url = URL.createObjectURL(blob);

  const sanitizedName = projectName.replace(/[^a-zA-Z0-9_-]/g, "_").toLowerCase() || "simulation";
  const filename = `${sanitizedName}_simpy.ipynb`;

  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
